package generators

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"example.com/spoke-tool/api/types"
)

// TestTemplates provides language-specific test generation templates
// These templates are PURELY FOR GENERATING NEW TEST FILES - no source code changes
type TestTemplates struct {
	// Template functions available to all templates
	funcMap template.FuncMap
}

// TestData represents data passed to test templates
type TestData struct {
	// Package information
	PackageName string
	PackagePath string

	// Function being tested
	FunctionName string
	FunctionSig  string
	FunctionCode string

	// Language
	Language types.Language

	// Test cases
	TestCases []TestCaseData

	// Mock dependencies
	Mocks []MockData

	// Imports needed
	Imports []string

	// Custom setup/teardown
	SetupCode    string
	TeardownCode string

	// File header comments
	HeaderComment string

	// Whether to include benchmarks
	IncludeBenchmarks bool

	// Whether to include examples
	IncludeExamples bool
}

// TestCaseData represents a single test case
type TestCaseData struct {
	// Test name
	Name string

	// Description of what this test verifies
	Description string

	// Input values
	Inputs map[string]string

	// Expected output
	Expected string

	// Whether this test should expect an error
	ExpectError bool

	// Expected error message (if expecting error)
	ErrorMessage string

	// Whether this is an edge case
	IsEdgeCase bool

	// Setup specific to this test
	Setup string

	// Teardown specific to this test
	Teardown string

	// Sub-tests for table-driven or parameterized tests
	SubTests []TestCaseData
}

// MockData represents a mock dependency
type MockData struct {
	// Name of the mock
	Name string

	// Type/interface being mocked
	Type string

	// Methods to mock
	Methods []MockMethod

	// Return values
	Returns map[string]string
}

// MockMethod represents a method to mock
type MockMethod struct {
	Name       string
	Parameters []string
	Returns    []string
}

// NewTestTemplates creates a new test templates instance
func NewTestTemplates() *TestTemplates {
	return &TestTemplates{
		funcMap: template.FuncMap{
			"lower":         strings.ToLower,
			"upper":         strings.ToUpper,
			"title":         strings.Title,
			"trim":          strings.TrimSpace,
			"join":          strings.Join,
			"split":         strings.Split,
			"indent":        indent,
			"now":           getCurrentTime,
			"hasPrefix":     strings.HasPrefix,
			"hasSuffix":     strings.HasSuffix,
			"replace":       strings.ReplaceAll,
			"quote":         quoteString,
			"formatInputs":  formatInputs,
			"formatReturns": formatReturns,
			"inc":           func(i int) int { return i + 1 },
		},
	}
}

// GetTestFileTemplate returns the appropriate template for a test file
func (t *TestTemplates) GetTestFileTemplate(lang types.Language) string {
	switch lang {
	case types.Go:
		return t.getGoTestFileTemplate()
	case types.NodeJS:
		return t.getNodeJSTestFileTemplate()
	case types.Python:
		return t.getPythonTestFileTemplate()
	default:
		return t.getDefaultTestFileTemplate()
	}
}

// GetTestCaseTemplate returns the appropriate template for test cases
func (t *TestTemplates) GetTestCaseTemplate(lang types.Language) string {
	switch lang {
	case types.Go:
		return t.getGoTestCaseTemplate()
	case types.NodeJS:
		return t.getNodeJSTestCaseTemplate()
	case types.Python:
		return t.getPythonTestCaseTemplate()
	default:
		return t.getDefaultTestCaseTemplate()
	}
}

// GetBenchmarkTemplate returns the appropriate template for benchmarks
func (t *TestTemplates) GetBenchmarkTemplate(lang types.Language) string {
	switch lang {
	case types.Go:
		return t.getGoBenchmarkTemplate()
	case types.NodeJS:
		return t.getNodeJSBenchmarkTemplate()
	case types.Python:
		return t.getPythonBenchmarkTemplate()
	default:
		return ""
	}
}

// GetMockTemplate returns the appropriate template for mocks
func (t *TestTemplates) GetMockTemplate(lang types.Language) string {
	switch lang {
	case types.Go:
		return t.getGoMockTemplate()
	case types.NodeJS:
		return t.getNodeJSMockTemplate()
	case types.Python:
		return t.getPythonMockTemplate()
	default:
		return ""
	}
}

// Go templates

func (t *TestTemplates) getGoTestFileTemplate() string {
	return `// Code generated by spoke-tool. DO NOT EDIT.
{{if .HeaderComment}}{{.HeaderComment}}
{{end}}package {{.PackageName}}

import (
	"testing"
	{{range .Imports}}"{{.}}"
	{{end}}
)

{{if .SetupCode}}
func setup() {
{{.SetupCode | indent 1}}
}

func teardown() {
{{.TeardownCode | indent 1}}
}
{{end}}

{{range .TestCases}}
{{template "go_test_case" .}}
{{end}}

{{if .IncludeBenchmarks}}
{{template "go_benchmark" .}}
{{end}}
`
}

func (t *TestTemplates) getGoTestCaseTemplate() string {
	return `{{define "go_test_case"}}func Test{{.Name}}(t *testing.T) {
	{{if .Setup}}// Setup
	{{.Setup}}
	{{end}}
	tests := []struct {
		name    string
		{{range $key, $value := .Inputs}}{{$key}} {{$value | typeFromValue}}
		{{end}}want    {{.Expected | typeFromValue}}
		wantErr bool
	}{
		{{range $i, $tc := .SubTests}}{
			name: "{{$tc.Name}}",
			{{range $key, $value := $tc.Inputs}}{{$key}}: {{$value}},
			{{end}}want: {{$tc.Expected}},
			wantErr: {{$tc.ExpectError}},
		},
		{{end}}
	}
	
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			{{if .ExpectError}}got, err := {{$.FunctionName}}({{range $key, $value := .Inputs}}tt.{{$key}}, {{end}})
			if (err != nil) != tt.wantErr {
				t.Errorf("{{$.FunctionName}}() error = %v, wantErr %v", err, tt.wantErr)
				return
			}
			if !tt.wantErr && got != tt.want {
				t.Errorf("{{$.FunctionName}}() = %v, want %v", got, tt.want)
			}{{else}}got := {{$.FunctionName}}({{range $key, $value := .Inputs}}tt.{{$key}}, {{end}})
			if got != tt.want {
				t.Errorf("{{$.FunctionName}}() = %v, want %v", got, tt.want)
			}{{end}}
		})
	}
	{{if .Teardown}}
	// Teardown
	{{.Teardown}}
	{{end}}
}
{{end}}`
}

func (t *TestTemplates) getGoBenchmarkTemplate() string {
	return `{{define "go_benchmark"}}func Benchmark{{.FunctionName}}(b *testing.B) {
	for i := 0; i < b.N; i++ {
		{{.FunctionName}}({{range $key, $value := .BenchmarkInputs}}{{$value}}, {{end}})
	}
}
{{end}}`
}

func (t *TestTemplates) getGoMockTemplate() string {
	return `{{define "go_mock"}}type Mock{{.Name}} struct {
	{{range .Methods}}Called{{.Name}} bool
	{{end}}}
}

{{range .Methods}}
func (m *Mock{{$.Name}}) {{.Name}}({{range $i, $p := .Parameters}}p{{$i}} {{$p}}{{if $i}}, {{end}}{{end}}) ({{join .Returns ", "}}) {
	m.Called{{.Name}} = true
	return {{range $i, $r := .Returns}}mock{{$i}}{{if $i}}, {{end}}{{end}}
}
{{end}}
{{end}}`
}

// Node.js/Jest templates

func (t *TestTemplates) getNodeJSTestFileTemplate() string {
	return `// Code generated by spoke-tool. DO NOT EDIT.
{{if .HeaderComment}}/**
 * {{.HeaderComment}}
 */
{{end}}
{{range .Imports}}const {{.Name}} = require('{{.Path}}');
{{end}}

{{if .SetupCode}}beforeEach(() => {
  {{.SetupCode | indent 2}}
});

afterEach(() => {
  {{.TeardownCode | indent 2}}
});
{{end}}

{{range .TestCases}}
{{template "nodejs_test_case" .}}
{{end}}

{{if .IncludeBenchmarks}}
{{template "nodejs_benchmark" .}}
{{end}}
`
}

func (t *TestTemplates) getNodeJSTestCaseTemplate() string {
	return `{{define "nodejs_test_case"}}describe('{{$.FunctionName}}', () => {
  {{if .Description}}/**
   * {{.Description}}
   */
  {{end}}{{range .SubTests}}test('{{.Name}}', () => {
    {{if .Setup}}{{.Setup}}
    {{end}}{{if .ExpectError}}expect(() => {{$.FunctionName}}({{range $key, $value := .Inputs}}{{$value}}, {{end}})).toThrow({{if .ErrorMessage}}"{{.ErrorMessage}}"{{end}});
    {{else}}const result = {{$.FunctionName}}({{range $key, $value := .Inputs}}{{$value}}, {{end}});
    expect(result).{{if .Expected | isEqual}}toEqual({{.Expected}}){{else}}toBe({{.Expected}}){{end}};{{end}}
    {{if .Teardown}}{{.Teardown}}
    {{end}}});
  {{end}});
});
{{end}}`
}

func (t *TestTemplates) getNodeJSBenchmarkTemplate() string {
	return `{{define "nodejs_benchmark"}}// Benchmarks (run with: node --test --benchmark)
test('{{.FunctionName}} benchmark', () => {
  const start = performance.now();
  for (let i = 0; i < 1000; i++) {
    {{.FunctionName}}({{range $key, $value := .BenchmarkInputs}}{{$value}}, {{end}});
  }
  const duration = performance.now() - start;
  console.log(` + "`" + `{{.FunctionName}} benchmark: ${duration}ms` + "`" + `);
});
{{end}}`
}

func (t *TestTemplates) getNodeJSMockTemplate() string {
	return `{{define "nodejs_mock"}}// Mock for {{.Name}}
const mock{{.Name}} = {
  {{range .Methods}}{{.Name}}: jest.fn({{if .Returns}}() => {{index .Returns 0}}{{end}}),
  {{end}}};

// Mock factory
const createMock{{.Name}} = (overrides = {}) => {
  return {
    ...mock{{.Name}},
    ...overrides
  };
};
{{end}}`
}

// Python/pytest templates

func (t *TestTemplates) getPythonTestFileTemplate() string {
	return `# Code generated by spoke-tool. DO NOT EDIT.
{{if .HeaderComment}}"""{{.HeaderComment}}"""
{{end}}
import pytest
{{range .Imports}}import {{.}}
{{end}}

{{if .SetupCode}}@pytest.fixture
def setup():
    {{.SetupCode | indent 4}}
    yield
    {{.TeardownCode | indent 4}}
{{end}}

{{range .TestCases}}
{{template "python_test_case" .}}
{{end}}

{{if .IncludeBenchmarks}}
{{template "python_benchmark" .}}
{{end}}
`
}

func (t *TestTemplates) getPythonTestCaseTemplate() string {
	return `{{define "python_test_case"}}{{if .Description}}"""
{{.Description}}
"""{{end}}
{{range .SubTests}}@pytest.mark.parametrize("{{range $key, $value := .Inputs}}{{$key}},{{end}}expected", [
    {{if .ExpectError}}pytest.param({{range $key, $value := .Inputs}}{{$value}}, {{end}}None, marks=pytest.mark.xfail(raises={{.ErrorMessage}})){{else}}({{range $key, $value := .Inputs}}{{$value}}, {{end}}{{.Expected}}),{{end}}
])
def test_{{$.FunctionName}}_{{.Name | snakeCase}}({{if $.SetupCode}}setup, {{end}}{{range $key, $value := .Inputs}}{{$key}}, {{end}}expected):
    {{if .ExpectError}}with pytest.raises({{.ErrorMessage}}):
        {{$.FunctionName}}({{range $key, $value := .Inputs}}{{$key}}, {{end}})
    {{else}}assert {{$.FunctionName}}({{range $key, $value := .Inputs}}{{$key}}, {{end}}) == expected{{end}}
{{end}}
{{end}}`
}

func (t *TestTemplates) getPythonBenchmarkTemplate() string {
	return `{{define "python_benchmark"}}def test_{{.FunctionName}}_benchmark(benchmark):
    result = benchmark({{.FunctionName}}, {{range $key, $value := .BenchmarkInputs}}{{$value}}, {{end}})
    assert result is not None
{{end}}`
}

func (t *TestTemplates) getPythonMockTemplate() string {
	return `{{define "python_mock"}}from unittest.mock import Mock, patch

# Mock for {{.Name}}
class Mock{{.Name}}:
    {{range .Methods}}def {{.Name}}(self, {{range $i, $p := .Parameters}}p{{$i}}{{if $i}}, {{end}}{{end}}):
        return {{index .Returns 0}}
    {{end}}

@pytest.fixture
def mock_{{.Name | lower}}():
    return Mock{{.Name}}()
{{end}}`
}

// Default templates (fallback)

func (t *TestTemplates) getDefaultTestFileTemplate() string {
	return `// Code generated by spoke-tool. DO NOT EDIT.
// Tests for {{.FunctionName}}

{{range .TestCases}}
{{template "default_test_case" .}}
{{end}}
`
}

func (t *TestTemplates) getDefaultTestCaseTemplate() string {
	return `{{define "default_test_case"}}# Test: {{.Name}}
# {{.Description}}

Inputs: {{range $key, $value := .Inputs}} {{$key}}={{$value}}{{end}}
Expected: {{.Expected}}
{{if .IsEdgeCase}}# Edge case
{{end}}
{{end}}`
}

// Template execution methods

// ExecuteTestFile executes the test file template with the given data
func (t *TestTemplates) ExecuteTestFile(data *TestData) (string, error) {
	tmpl := t.GetTestFileTemplate(data.Language)

	// Register test case template
	testCaseTmpl := t.GetTestCaseTemplate(data.Language)

	fullTmpl := testCaseTmpl + "\n" + tmpl

	return t.ExecuteTemplate(fullTmpl, data)
}

// ExecuteTemplate executes a template with the given data
func (t *TestTemplates) ExecuteTemplate(tmplStr string, data interface{}) (string, error) {
	tmpl, err := template.New("test").Funcs(t.funcMap).Parse(tmplStr)
	if err != nil {
		return "", err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}

	return buf.String(), nil
}

// Helper functions for templates

func quoteString(s string) string {
	return fmt.Sprintf("%q", s)
}

func formatInputs(inputs map[string]string) string {
	var parts []string
	for k, v := range inputs {
		parts = append(parts, fmt.Sprintf("%s: %s", k, v))
	}
	return strings.Join(parts, ", ")
}

func formatReturns(returns []string) string {
	if len(returns) == 0 {
		return ""
	}
	if len(returns) == 1 {
		return returns[0]
	}
	return "(" + strings.Join(returns, ", ") + ")"
}

// Template function to convert to snake_case
func toSnakeCase(s string) string {
	var result []rune
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result = append(result, '_')
		}
		result = append(result, r)
	}
	return strings.ToLower(string(result))
}

// Template function to get type from value
func typeFromValue(value string) string {
	// Simple type inference for template
	if strings.Contains(value, "\"") {
		return "string"
	}
	if strings.Contains(value, ".") {
		return "float64"
	}
	if value == "true" || value == "false" {
		return "bool"
	}
	return "int"
}

// Template function to check if expected value uses toEqual vs toBe
func isEqual(expected string) bool {
	// Simple heuristic: use toEqual for objects/arrays
	return strings.Contains(expected, "{") || strings.Contains(expected, "[")
}

// Predefined test case collections

// GetStandardTestCases returns standard test cases for a function
func (t *TestTemplates) GetStandardTestCases(funcName string) []TestCaseData {
	return []TestCaseData{
		{
			Name:        "Happy path",
			Description: "Test with normal inputs",
			IsEdgeCase:  false,
		},
		{
			Name:        "Edge case - zero values",
			Description: "Test with zero values",
			IsEdgeCase:  true,
		},
		{
			Name:        "Edge case - negative values",
			Description: "Test with negative values",
			IsEdgeCase:  true,
		},
		{
			Name:        "Error case",
			Description: "Test error condition",
			ExpectError: true,
			IsEdgeCase:  true,
		},
	}
}

// GetTableDrivenTestCases returns table-driven test cases (Go style)
func (t *TestTemplates) GetTableDrivenTestCases() []TestCaseData {
	return []TestCaseData{
		{
			Name: "test cases",
			SubTests: []TestCaseData{
				{Name: "case 1", Inputs: map[string]string{"a": "1", "b": "2"}, Expected: "3"},
				{Name: "case 2", Inputs: map[string]string{"a": "0", "b": "0"}, Expected: "0"},
				{Name: "case 3", Inputs: map[string]string{"a": "-1", "b": "1"}, Expected: "0"},
			},
		},
	}
}

// GetParameterizedTestCases returns parameterized test cases (pytest style)
func (t *TestTemplates) GetParameterizedTestCases() []TestCaseData {
	return []TestCaseData{
		{
			Name: "parametrized",
			SubTests: []TestCaseData{
				{Inputs: map[string]string{"a": "1", "b": "2"}, Expected: "3"},
				{Inputs: map[string]string{"a": "0", "b": "0"}, Expected: "0"},
				{Inputs: map[string]string{"a": "-1", "b": "1"}, Expected: "0"},
			},
		},
	}
}

// GetTestFileName returns the standard test file name for a source file
func (t *TestTemplates) GetTestFileName(sourceFile string, lang types.Language) string {
	switch lang {
	case types.Go:
		// math.go -> math_test.go
		if strings.HasSuffix(sourceFile, ".go") {
			return strings.TrimSuffix(sourceFile, ".go") + "_test.go"
		}
	case types.NodeJS:
		// math.js -> math.test.js
		if strings.HasSuffix(sourceFile, ".js") {
			return strings.TrimSuffix(sourceFile, ".js") + ".test.js"
		}
		if strings.HasSuffix(sourceFile, ".ts") {
			return strings.TrimSuffix(sourceFile, ".ts") + ".test.ts"
		}
	case types.Python:
		// math.py -> test_math.py
		if strings.HasSuffix(sourceFile, ".py") {
			return "test_" + sourceFile
		}
	}
	return "test_" + sourceFile
}

// GetPackageName extracts package name from file path
func (t *TestTemplates) GetPackageName(filePath string, lang types.Language) string {
	switch lang {
	case types.Go:
		// For Go, package name is often the directory name
		parts := strings.Split(filePath, "/")
		if len(parts) > 0 {
			return parts[len(parts)-1]
		}
	case types.NodeJS:
		// For Node.js, we might not need package name in tests
		return ""
	case types.Python:
		// For Python, we might not need package name in tests
		return ""
	}
	return "main"
}
